// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_roles.sql

package db

import (
	"context"
)

const addAdminRole = `-- name: AddAdminRole :exec
INSERT INTO admin_roles (guild_id, role_id, added_by)
VALUES ($1, $2, $3)
ON CONFLICT (guild_id, role_id) DO NOTHING
`

type AddAdminRoleParams struct {
	GuildID string `json:"guild_id"`
	RoleID  string `json:"role_id"`
	AddedBy string `json:"added_by"`
}

func (q *Queries) AddAdminRole(ctx context.Context, arg AddAdminRoleParams) error {
	_, err := q.db.Exec(ctx, addAdminRole, arg.GuildID, arg.RoleID, arg.AddedBy)
	return err
}

const getAdminRoles = `-- name: GetAdminRoles :many
SELECT role_id FROM admin_roles
WHERE guild_id = $1
`

func (q *Queries) GetAdminRoles(ctx context.Context, guildID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAdminRoles, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAdminRoles = `-- name: GetAllAdminRoles :many
SELECT guild_id, role_id FROM admin_roles
ORDER BY guild_id, role_id
`

type GetAllAdminRolesRow struct {
	GuildID string `json:"guild_id"`
	RoleID  string `json:"role_id"`
}

func (q *Queries) GetAllAdminRoles(ctx context.Context) ([]GetAllAdminRolesRow, error) {
	rows, err := q.db.Query(ctx, getAllAdminRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllAdminRolesRow{}
	for rows.Next() {
		var i GetAllAdminRolesRow
		if err := rows.Scan(&i.GuildID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAdminRole = `-- name: RemoveAdminRole :exec
DELETE FROM admin_roles
WHERE guild_id = $1 AND role_id = $2
`

type RemoveAdminRoleParams struct {
	GuildID string `json:"guild_id"`
	RoleID  string `json:"role_id"`
}

func (q *Queries) RemoveAdminRole(ctx context.Context, arg RemoveAdminRoleParams) error {
	_, err := q.db.Exec(ctx, removeAdminRole, arg.GuildID, arg.RoleID)
	return err
}
