// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelActivityTimeline = `-- name: GetChannelActivityTimeline :many
SELECT 
    date_trunc('hour', time)::timestamp AS interval_start,
    user_id,
    COUNT(*) as message_count
FROM discord_messages
WHERE channel_id = $1
  AND server_id = $2
  AND time >= NOW() - INTERVAL '24 hours'
GROUP BY interval_start, user_id
ORDER BY interval_start, message_count DESC
`

type GetChannelActivityTimelineParams struct {
	ChannelID string `json:"channel_id"`
	ServerID  string `json:"server_id"`
}

type GetChannelActivityTimelineRow struct {
	IntervalStart pgtype.Timestamp `json:"interval_start"`
	UserID        string           `json:"user_id"`
	MessageCount  int64            `json:"message_count"`
}

// Get message counts per user in hourly intervals for a channel in the last 24 hours
func (q *Queries) GetChannelActivityTimeline(ctx context.Context, arg GetChannelActivityTimelineParams) ([]GetChannelActivityTimelineRow, error) {
	rows, err := q.db.Query(ctx, getChannelActivityTimeline, arg.ChannelID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChannelActivityTimelineRow{}
	for rows.Next() {
		var i GetChannelActivityTimelineRow
		if err := rows.Scan(&i.IntervalStart, &i.UserID, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelPeakHours = `-- name: GetChannelPeakHours :many
SELECT 
    EXTRACT(HOUR FROM time)::int as hour_of_day,
    COUNT(*)::bigint as message_count,
    COUNT(DISTINCT user_id)::bigint as unique_users,
    COUNT(DISTINCT DATE(time))::bigint as days_with_activity
FROM discord_messages
WHERE server_id = $1
  AND ($2::text IS NULL OR channel_id = $2)
  AND time > NOW() - INTERVAL '30 days'
GROUP BY hour_of_day
ORDER BY hour_of_day
`

type GetChannelPeakHoursParams struct {
	ServerID  string `json:"server_id"`
	ChannelID string `json:"channel_id"`
}

type GetChannelPeakHoursRow struct {
	HourOfDay        int32 `json:"hour_of_day"`
	MessageCount     int64 `json:"message_count"`
	UniqueUsers      int64 `json:"unique_users"`
	DaysWithActivity int64 `json:"days_with_activity"`
}

// Get hourly activity patterns for a channel over the last 30 days
func (q *Queries) GetChannelPeakHours(ctx context.Context, arg GetChannelPeakHoursParams) ([]GetChannelPeakHoursRow, error) {
	rows, err := q.db.Query(ctx, getChannelPeakHours, arg.ServerID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChannelPeakHoursRow{}
	for rows.Next() {
		var i GetChannelPeakHoursRow
		if err := rows.Scan(
			&i.HourOfDay,
			&i.MessageCount,
			&i.UniqueUsers,
			&i.DaysWithActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRisingStars = `-- name: GetRisingStars :many
WITH user_activity AS (
    SELECT 
        user_id,
        COUNT(*) FILTER (WHERE time > NOW() - INTERVAL '7 days') as this_week,
        COUNT(*) FILTER (WHERE time > NOW() - INTERVAL '14 days' AND time <= NOW() - INTERVAL '7 days') as last_week,
        COUNT(*) FILTER (WHERE time > NOW() - INTERVAL '30 days') as last_30_days,
        MIN(time) as first_message_time
    FROM discord_messages
    WHERE server_id = $2
    GROUP BY user_id
    HAVING COUNT(*) FILTER (WHERE time > NOW() - INTERVAL '7 days') >= 10 -- Minimum activity threshold
),
growth_metrics AS (
    SELECT 
        user_id,
        this_week,
        last_week,
        last_30_days,
        first_message_time,
        CASE 
            WHEN last_week > 0 THEN ((this_week - last_week)::float / last_week * 100)
            ELSE 100
        END as growth_rate,
        -- Calculate consistency score (messages per day average)
        last_30_days::float / 30 as daily_average
    FROM user_activity
    WHERE first_message_time < NOW() - INTERVAL '14 days' -- Not brand new users
)
SELECT 
    user_id,
    this_week::bigint,
    last_week::bigint,
    last_30_days::bigint,
    growth_rate::float8,
    daily_average::float8,
    first_message_time
FROM growth_metrics
WHERE growth_rate > 20 -- At least 20% growth
  AND this_week > last_week -- Ensure positive growth
ORDER BY growth_rate DESC
LIMIT $1
`

type GetRisingStarsParams struct {
	LimitCount int32  `json:"limit_count"`
	ServerID   string `json:"server_id"`
}

type GetRisingStarsRow struct {
	UserID           string      `json:"user_id"`
	ThisWeek         int64       `json:"this_week"`
	LastWeek         int64       `json:"last_week"`
	Last30Days       int64       `json:"last_30_days"`
	GrowthRate       float64     `json:"growth_rate"`
	DailyAverage     float64     `json:"daily_average"`
	FirstMessageTime interface{} `json:"first_message_time"`
}

// Find users with significant positive activity trends
func (q *Queries) GetRisingStars(ctx context.Context, arg GetRisingStarsParams) ([]GetRisingStarsRow, error) {
	rows, err := q.db.Query(ctx, getRisingStars, arg.LimitCount, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRisingStarsRow{}
	for rows.Next() {
		var i GetRisingStarsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ThisWeek,
			&i.LastWeek,
			&i.Last30Days,
			&i.GrowthRate,
			&i.DailyAverage,
			&i.FirstMessageTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
