// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"
	"time"
)

const getChattiestUsers = `-- name: GetChattiestUsers :many
SELECT user_id, COUNT(*) as message_count
FROM discord_messages
WHERE server_id = $1
  AND channel_id = $2
  AND time > CASE 
    WHEN $3 = 'today' THEN NOW() - INTERVAL '1 day'
    WHEN $3 = 'yesterday' THEN NOW() - INTERVAL '2 days'
    WHEN $3 = 'week' THEN NOW() - INTERVAL '7 days'
    WHEN $3 = 'month' THEN NOW() - INTERVAL '30 days'
    ELSE NOW() - INTERVAL '7 days'
  END
  AND ($3 != 'yesterday' OR time <= NOW() - INTERVAL '1 day')
GROUP BY user_id
ORDER BY message_count DESC
LIMIT $4
`

type GetChattiestUsersParams struct {
	ServerID   string      `json:"server_id"`
	ChannelID  string      `json:"channel_id"`
	Period     interface{} `json:"period"`
	LimitCount int32       `json:"limit_count"`
}

type GetChattiestUsersRow struct {
	UserID       string `json:"user_id"`
	MessageCount int64  `json:"message_count"`
}

func (q *Queries) GetChattiestUsers(ctx context.Context, arg GetChattiestUsersParams) ([]GetChattiestUsersRow, error) {
	rows, err := q.db.Query(ctx, getChattiestUsers,
		arg.ServerID,
		arg.ChannelID,
		arg.Period,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChattiestUsersRow{}
	for rows.Next() {
		var i GetChattiestUsersRow
		if err := rows.Scan(&i.UserID, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInactiveChannels = `-- name: GetInactiveChannels :many
WITH channel_activity AS (
    SELECT 
        channel_id,
        MAX(time) as last_message_time,
        COUNT(*) as total_messages,
        COUNT(DISTINCT user_id) as unique_users
    FROM discord_messages
    WHERE discord_messages.server_id = $3
    GROUP BY channel_id
)
SELECT 
    channel_id,
    last_message_time,
    total_messages::bigint,
    unique_users::bigint,
    EXTRACT(EPOCH FROM (NOW() - last_message_time)) / 604800 as weeks_inactive
FROM channel_activity
WHERE last_message_time < NOW() - ($1::int || ' weeks')::interval
ORDER BY last_message_time DESC
LIMIT $2
`

type GetInactiveChannelsParams struct {
	Weeks      int32  `json:"weeks"`
	LimitCount int32  `json:"limit_count"`
	ServerID   string `json:"server_id"`
}

type GetInactiveChannelsRow struct {
	ChannelID       string      `json:"channel_id"`
	LastMessageTime interface{} `json:"last_message_time"`
	TotalMessages   int64       `json:"total_messages"`
	UniqueUsers     int64       `json:"unique_users"`
	WeeksInactive   int32       `json:"weeks_inactive"`
}

// Find channels that haven't had posts in N weeks
func (q *Queries) GetInactiveChannels(ctx context.Context, arg GetInactiveChannelsParams) ([]GetInactiveChannelsRow, error) {
	rows, err := q.db.Query(ctx, getInactiveChannels, arg.Weeks, arg.LimitCount, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInactiveChannelsRow{}
	for rows.Next() {
		var i GetInactiveChannelsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LastMessageTime,
			&i.TotalMessages,
			&i.UniqueUsers,
			&i.WeeksInactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInactiveUsers = `-- name: GetInactiveUsers :many
WITH server_users AS (
    -- Get all users who have ever posted in the server
    SELECT DISTINCT user_id
    FROM discord_messages
    WHERE discord_messages.server_id = $2
),
recent_activity AS (
    -- Get users who posted within the inactive period
    SELECT DISTINCT user_id
    FROM discord_messages
    WHERE discord_messages.server_id = $2
      AND time > NOW() - ($3::int || ' days')::interval
),
last_activity AS (
    -- Get last message time for all users
    SELECT 
        user_id,
        MAX(time) as last_message_time,
        COUNT(*) as total_messages
    FROM discord_messages
    WHERE discord_messages.server_id = $2
    GROUP BY user_id
)
SELECT 
    su.user_id,
    COALESCE(la.last_message_time, NULL) as last_message_time,
    COALESCE(la.total_messages, 0)::bigint as total_messages,
    EXTRACT(EPOCH FROM (NOW() - la.last_message_time)) / 86400 as days_inactive
FROM server_users su
LEFT JOIN last_activity la ON su.user_id = la.user_id
WHERE su.user_id NOT IN (SELECT user_id FROM recent_activity)
  AND la.last_message_time IS NOT NULL
ORDER BY la.last_message_time DESC
LIMIT $1
`

type GetInactiveUsersParams struct {
	LimitCount int32  `json:"limit_count"`
	ServerID   string `json:"server_id"`
	Days       int32  `json:"days"`
}

type GetInactiveUsersRow struct {
	UserID          string      `json:"user_id"`
	LastMessageTime interface{} `json:"last_message_time"`
	TotalMessages   int64       `json:"total_messages"`
	DaysInactive    int32       `json:"days_inactive"`
}

// Find users who haven't posted in N days
func (q *Queries) GetInactiveUsers(ctx context.Context, arg GetInactiveUsersParams) ([]GetInactiveUsersRow, error) {
	rows, err := q.db.Query(ctx, getInactiveUsers, arg.LimitCount, arg.ServerID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInactiveUsersRow{}
	for rows.Next() {
		var i GetInactiveUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.LastMessageTime,
			&i.TotalMessages,
			&i.DaysInactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerActivitySummary = `-- name: GetServerActivitySummary :one
WITH time_periods AS (
    SELECT 
        COUNT(DISTINCT user_id) FILTER (WHERE time > NOW() - INTERVAL '1 day') as active_users_today,
        COUNT(DISTINCT user_id) FILTER (WHERE time > NOW() - INTERVAL '7 days') as active_users_week,
        COUNT(DISTINCT user_id) FILTER (WHERE time > NOW() - INTERVAL '30 days') as active_users_month,
        COUNT(DISTINCT channel_id) FILTER (WHERE time > NOW() - INTERVAL '1 day') as active_channels_today,
        COUNT(DISTINCT channel_id) FILTER (WHERE time > NOW() - INTERVAL '7 days') as active_channels_week,
        COUNT(DISTINCT channel_id) FILTER (WHERE time > NOW() - INTERVAL '30 days') as active_channels_month,
        COUNT(*) FILTER (WHERE time > NOW() - INTERVAL '1 day') as messages_today,
        COUNT(*) FILTER (WHERE time > NOW() - INTERVAL '7 days') as messages_week,
        COUNT(*) FILTER (WHERE time > NOW() - INTERVAL '30 days') as messages_month
    FROM discord_messages
    WHERE discord_messages.server_id = $1
),
total_stats AS (
    SELECT 
        COUNT(DISTINCT user_id) as total_users,
        COUNT(DISTINCT channel_id) as total_channels,
        COUNT(*) as total_messages
    FROM discord_messages
    WHERE discord_messages.server_id = $1
)
SELECT 
    COALESCE(tp.active_users_today, 0)::bigint as active_users_today,
    COALESCE(tp.active_users_week, 0)::bigint as active_users_week,
    COALESCE(tp.active_users_month, 0)::bigint as active_users_month,
    COALESCE(tp.active_channels_today, 0)::bigint as active_channels_today,
    COALESCE(tp.active_channels_week, 0)::bigint as active_channels_week,
    COALESCE(tp.active_channels_month, 0)::bigint as active_channels_month,
    COALESCE(tp.messages_today, 0)::bigint as messages_today,
    COALESCE(tp.messages_week, 0)::bigint as messages_week,
    COALESCE(tp.messages_month, 0)::bigint as messages_month,
    COALESCE(ts.total_users, 0)::bigint as total_users,
    COALESCE(ts.total_channels, 0)::bigint as total_channels,
    COALESCE(ts.total_messages, 0)::bigint as total_messages
FROM time_periods tp, total_stats ts
`

type GetServerActivitySummaryRow struct {
	ActiveUsersToday    int64 `json:"active_users_today"`
	ActiveUsersWeek     int64 `json:"active_users_week"`
	ActiveUsersMonth    int64 `json:"active_users_month"`
	ActiveChannelsToday int64 `json:"active_channels_today"`
	ActiveChannelsWeek  int64 `json:"active_channels_week"`
	ActiveChannelsMonth int64 `json:"active_channels_month"`
	MessagesToday       int64 `json:"messages_today"`
	MessagesWeek        int64 `json:"messages_week"`
	MessagesMonth       int64 `json:"messages_month"`
	TotalUsers          int64 `json:"total_users"`
	TotalChannels       int64 `json:"total_channels"`
	TotalMessages       int64 `json:"total_messages"`
}

// Get overall server activity metrics
func (q *Queries) GetServerActivitySummary(ctx context.Context, serverID string) (GetServerActivitySummaryRow, error) {
	row := q.db.QueryRow(ctx, getServerActivitySummary, serverID)
	var i GetServerActivitySummaryRow
	err := row.Scan(
		&i.ActiveUsersToday,
		&i.ActiveUsersWeek,
		&i.ActiveUsersMonth,
		&i.ActiveChannelsToday,
		&i.ActiveChannelsWeek,
		&i.ActiveChannelsMonth,
		&i.MessagesToday,
		&i.MessagesWeek,
		&i.MessagesMonth,
		&i.TotalUsers,
		&i.TotalChannels,
		&i.TotalMessages,
	)
	return i, err
}

const getTrendingUsers = `-- name: GetTrendingUsers :many
WITH weekly_stats AS (
    SELECT 
        user_id,
        COUNT(CASE WHEN time > NOW() - INTERVAL '7 days' THEN 1 END) as this_week,
        COUNT(CASE WHEN time > NOW() - INTERVAL '14 days' 
                   AND time <= NOW() - INTERVAL '7 days' THEN 1 END) as last_week
    FROM discord_messages
    WHERE server_id = $2
      AND time > NOW() - INTERVAL '14 days'
    GROUP BY user_id
    HAVING COUNT(CASE WHEN time > NOW() - INTERVAL '7 days' THEN 1 END) > 10
)
SELECT 
    user_id,
    this_week::bigint,
    last_week::bigint,
    CASE 
        WHEN last_week > 0 THEN 
            ROUND(100.0 * (this_week - last_week) / last_week, 1)
        ELSE 100
    END::float8 as percent_change
FROM weekly_stats
WHERE this_week != last_week
ORDER BY percent_change DESC
LIMIT $1
`

type GetTrendingUsersParams struct {
	LimitCount int32  `json:"limit_count"`
	ServerID   string `json:"server_id"`
}

type GetTrendingUsersRow struct {
	UserID        string  `json:"user_id"`
	ThisWeek      int64   `json:"this_week"`
	LastWeek      int64   `json:"last_week"`
	PercentChange float64 `json:"percent_change"`
}

func (q *Queries) GetTrendingUsers(ctx context.Context, arg GetTrendingUsersParams) ([]GetTrendingUsersRow, error) {
	rows, err := q.db.Query(ctx, getTrendingUsers, arg.LimitCount, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrendingUsersRow{}
	for rows.Next() {
		var i GetTrendingUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.ThisWeek,
			&i.LastWeek,
			&i.PercentChange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDailyActivity = `-- name: GetUserDailyActivity :many
SELECT 
    time_bucket('1 day', time) AS day,
    COUNT(*) as message_count
FROM discord_messages
WHERE user_id = $1
  AND server_id = $2
  AND time > NOW() - INTERVAL '30 days'
GROUP BY day
ORDER BY day DESC
`

type GetUserDailyActivityParams struct {
	UserID   string `json:"user_id"`
	ServerID string `json:"server_id"`
}

type GetUserDailyActivityRow struct {
	Day          interface{} `json:"day"`
	MessageCount int64       `json:"message_count"`
}

func (q *Queries) GetUserDailyActivity(ctx context.Context, arg GetUserDailyActivityParams) ([]GetUserDailyActivityRow, error) {
	rows, err := q.db.Query(ctx, getUserDailyActivity, arg.UserID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserDailyActivityRow{}
	for rows.Next() {
		var i GetUserDailyActivityRow
		if err := rows.Scan(&i.Day, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
WITH periods AS (
    SELECT 
        CASE 
            WHEN $1 = 'today' THEN '1 day'::interval
            WHEN $1 = 'week' THEN '7 days'::interval
            ELSE '30 days'::interval
        END as current_period
),
current_stats AS (
    SELECT 
        COUNT(*) as message_count,
        COUNT(DISTINCT discord_messages.channel_id) as channels_active,
        COUNT(DISTINCT DATE_TRUNC('day', discord_messages.time)) as days_active
    FROM discord_messages, periods
    WHERE discord_messages.user_id = $2
      AND discord_messages.server_id = $3
      AND discord_messages.time > NOW() - periods.current_period
),
previous_stats AS (
    SELECT COUNT(*) as prev_count
    FROM discord_messages, periods
    WHERE discord_messages.user_id = $2
      AND discord_messages.server_id = $3
      AND discord_messages.time > NOW() - (2 * periods.current_period)
      AND discord_messages.time <= NOW() - periods.current_period
)
SELECT 
    COALESCE(c.message_count, 0)::bigint as message_count,
    COALESCE(c.channels_active, 0)::bigint as channels_active,
    COALESCE(c.days_active, 0)::bigint as days_active,
    COALESCE(p.prev_count, 0)::bigint as prev_count,
    CASE 
        WHEN p.prev_count > 0 THEN 
            ROUND(100.0 * (c.message_count - p.prev_count) / p.prev_count, 1)
        ELSE 0
    END::float8 as percent_change
FROM current_stats c, previous_stats p
`

type GetUserStatsParams struct {
	Period   interface{} `json:"period"`
	UserID   string      `json:"user_id"`
	ServerID string      `json:"server_id"`
}

type GetUserStatsRow struct {
	MessageCount   int64   `json:"message_count"`
	ChannelsActive int64   `json:"channels_active"`
	DaysActive     int64   `json:"days_active"`
	PrevCount      int64   `json:"prev_count"`
	PercentChange  float64 `json:"percent_change"`
}

func (q *Queries) GetUserStats(ctx context.Context, arg GetUserStatsParams) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, arg.Period, arg.UserID, arg.ServerID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.MessageCount,
		&i.ChannelsActive,
		&i.DaysActive,
		&i.PrevCount,
		&i.PercentChange,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO discord_messages (
    time, user_id, channel_id, server_id, message_id
) VALUES (
    $1, $2, $3, $4, $5
) ON CONFLICT (message_id, time) DO NOTHING
`

type InsertMessageParams struct {
	Time      time.Time `json:"time"`
	UserID    string    `json:"user_id"`
	ChannelID string    `json:"channel_id"`
	ServerID  string    `json:"server_id"`
	MessageID string    `json:"message_id"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.Time,
		arg.UserID,
		arg.ChannelID,
		arg.ServerID,
		arg.MessageID,
	)
	return err
}
