// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminRole struct {
	GuildID string    `json:"guild_id"`
	RoleID  string    `json:"role_id"`
	AddedBy string    `json:"added_by"`
	AddedAt time.Time `json:"added_at"`
}

type DiscordMessage struct {
	Time      time.Time `json:"time"`
	UserID    string    `json:"user_id"`
	ChannelID string    `json:"channel_id"`
	ServerID  string    `json:"server_id"`
	MessageID string    `json:"message_id"`
}

type ResponseChannelConfig struct {
	GuildID      string    `json:"guild_id"`
	CommandName  string    `json:"command_name"`
	ChannelID    string    `json:"channel_id"`
	ConfiguredBy string    `json:"configured_by"`
	ConfiguredAt time.Time `json:"configured_at"`
}

type User struct {
	UserID        string             `json:"user_id"`
	Username      string             `json:"username"`
	Discriminator pgtype.Text        `json:"discriminator"`
	DisplayName   pgtype.Text        `json:"display_name"`
	AvatarHash    pgtype.Text        `json:"avatar_hash"`
	Bot           pgtype.Bool        `json:"bot"`
	FirstSeenAt   time.Time          `json:"first_seen_at"`
	LastUpdatedAt time.Time          `json:"last_updated_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	IsActive      pgtype.Bool        `json:"is_active"`
}

type UserDailyStat struct {
	Day          interface{} `json:"day"`
	ServerID     string      `json:"server_id"`
	UserID       string      `json:"user_id"`
	ChannelID    string      `json:"channel_id"`
	MessageCount int64       `json:"message_count"`
}

type UserHourlyStat struct {
	Hour         interface{} `json:"hour"`
	ServerID     string      `json:"server_id"`
	UserID       string      `json:"user_id"`
	ChannelID    string      `json:"channel_id"`
	MessageCount int64       `json:"message_count"`
}

// Tracks username changes over time. Retention: 2 years
type UsernameChangelog struct {
	ID               int64       `json:"id"`
	UserID           string      `json:"user_id"`
	OldUsername      string      `json:"old_username"`
	NewUsername      string      `json:"new_username"`
	OldDiscriminator pgtype.Text `json:"old_discriminator"`
	NewDiscriminator pgtype.Text `json:"new_discriminator"`
	ChangedAt        time.Time   `json:"changed_at"`
	DetectedVia      string      `json:"detected_via"`
}
