// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddAdminRole(ctx context.Context, arg AddAdminRoleParams) error
	BatchUpsertUser(ctx context.Context, arg BatchUpsertUserParams) error
	CleanupOldUsernameChanges(ctx context.Context) error
	// Clear all response channel configurations for a guild
	ClearAllResponseChannels(ctx context.Context, guildID string) error
	// Clear response channel configuration for a specific command
	ClearResponseChannel(ctx context.Context, arg ClearResponseChannelParams) error
	GetActiveUsers(ctx context.Context, limit int32) ([]User, error)
	GetAdminRoles(ctx context.Context, guildID string) ([]string, error)
	GetAllAdminRoles(ctx context.Context) ([]GetAllAdminRolesRow, error)
	// Get message counts per user in hourly intervals for a channel in the last 24 hours
	GetChannelActivityTimeline(ctx context.Context, arg GetChannelActivityTimelineParams) ([]GetChannelActivityTimelineRow, error)
	// Get hourly activity patterns for a channel over the last 30 days
	GetChannelPeakHours(ctx context.Context, arg GetChannelPeakHoursParams) ([]GetChannelPeakHoursRow, error)
	GetChattiestUsers(ctx context.Context, arg GetChattiestUsersParams) ([]GetChattiestUsersRow, error)
	// Get global response channel for a guild
	GetGlobalResponseChannel(ctx context.Context, guildID string) (GetGlobalResponseChannelRow, error)
	// Find channels that haven't had posts in N weeks
	GetInactiveChannels(ctx context.Context, arg GetInactiveChannelsParams) ([]GetInactiveChannelsRow, error)
	// Find users who haven't posted in N days
	GetInactiveUsers(ctx context.Context, arg GetInactiveUsersParams) ([]GetInactiveUsersRow, error)
	GetRecentUsernameChanges(ctx context.Context, limit int32) ([]GetRecentUsernameChangesRow, error)
	// Get response channel for a specific command
	GetResponseChannel(ctx context.Context, arg GetResponseChannelParams) (GetResponseChannelRow, error)
	// Find users with significant positive activity trends
	GetRisingStars(ctx context.Context, arg GetRisingStarsParams) ([]GetRisingStarsRow, error)
	// Get overall server activity metrics
	GetServerActivitySummary(ctx context.Context, serverID string) (GetServerActivitySummaryRow, error)
	GetStaleUsers(ctx context.Context, limit int32) ([]GetStaleUsersRow, error)
	GetTrendingUsers(ctx context.Context, arg GetTrendingUsersParams) ([]GetTrendingUsersRow, error)
	GetUser(ctx context.Context, userID string) (User, error)
	GetUserByUsername(ctx context.Context, username string) ([]User, error)
	GetUserDailyActivity(ctx context.Context, arg GetUserDailyActivityParams) ([]GetUserDailyActivityRow, error)
	GetUserProfile(ctx context.Context, userID string) (GetUserProfileRow, error)
	GetUserStats(ctx context.Context, arg GetUserStatsParams) (GetUserStatsRow, error)
	GetUsernameHistory(ctx context.Context, arg GetUsernameHistoryParams) ([]GetUsernameHistoryRow, error)
	GetUsersNeedingRefresh(ctx context.Context, limit int32) ([]string, error)
	GetUsersWithoutRecentActivity(ctx context.Context, limit int32) ([]GetUsersWithoutRecentActivityRow, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) error
	// List all response channel configurations for a guild
	ListResponseChannels(ctx context.Context, guildID string) ([]ListResponseChannelsRow, error)
	MarkUserInactive(ctx context.Context, userID string) error
	RemoveAdminRole(ctx context.Context, arg RemoveAdminRoleParams) error
	SearchUsersByPattern(ctx context.Context, arg SearchUsersByPatternParams) ([]User, error)
	// Set response channel for a command (empty command_name = global)
	SetResponseChannel(ctx context.Context, arg SetResponseChannelParams) error
	UpdateUserLastMessage(ctx context.Context, arg UpdateUserLastMessageParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
