// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: response_channels.sql

package db

import (
	"context"
	"time"
)

const clearAllResponseChannels = `-- name: ClearAllResponseChannels :exec
DELETE FROM response_channel_config
WHERE guild_id = $1
`

// Clear all response channel configurations for a guild
func (q *Queries) ClearAllResponseChannels(ctx context.Context, guildID string) error {
	_, err := q.db.Exec(ctx, clearAllResponseChannels, guildID)
	return err
}

const clearResponseChannel = `-- name: ClearResponseChannel :exec
DELETE FROM response_channel_config
WHERE guild_id = $1 AND command_name = $2
`

type ClearResponseChannelParams struct {
	GuildID     string `json:"guild_id"`
	CommandName string `json:"command_name"`
}

// Clear response channel configuration for a specific command
func (q *Queries) ClearResponseChannel(ctx context.Context, arg ClearResponseChannelParams) error {
	_, err := q.db.Exec(ctx, clearResponseChannel, arg.GuildID, arg.CommandName)
	return err
}

const getGlobalResponseChannel = `-- name: GetGlobalResponseChannel :one
SELECT channel_id, configured_by, configured_at
FROM response_channel_config
WHERE guild_id = $1 AND command_name = ''
`

type GetGlobalResponseChannelRow struct {
	ChannelID    string    `json:"channel_id"`
	ConfiguredBy string    `json:"configured_by"`
	ConfiguredAt time.Time `json:"configured_at"`
}

// Get global response channel for a guild
func (q *Queries) GetGlobalResponseChannel(ctx context.Context, guildID string) (GetGlobalResponseChannelRow, error) {
	row := q.db.QueryRow(ctx, getGlobalResponseChannel, guildID)
	var i GetGlobalResponseChannelRow
	err := row.Scan(&i.ChannelID, &i.ConfiguredBy, &i.ConfiguredAt)
	return i, err
}

const getResponseChannel = `-- name: GetResponseChannel :one
SELECT channel_id, configured_by, configured_at
FROM response_channel_config
WHERE guild_id = $1 AND command_name = $2
`

type GetResponseChannelParams struct {
	GuildID     string `json:"guild_id"`
	CommandName string `json:"command_name"`
}

type GetResponseChannelRow struct {
	ChannelID    string    `json:"channel_id"`
	ConfiguredBy string    `json:"configured_by"`
	ConfiguredAt time.Time `json:"configured_at"`
}

// Get response channel for a specific command
func (q *Queries) GetResponseChannel(ctx context.Context, arg GetResponseChannelParams) (GetResponseChannelRow, error) {
	row := q.db.QueryRow(ctx, getResponseChannel, arg.GuildID, arg.CommandName)
	var i GetResponseChannelRow
	err := row.Scan(&i.ChannelID, &i.ConfiguredBy, &i.ConfiguredAt)
	return i, err
}

const listResponseChannels = `-- name: ListResponseChannels :many
SELECT command_name, channel_id, configured_by, configured_at
FROM response_channel_config
WHERE guild_id = $1
ORDER BY command_name
`

type ListResponseChannelsRow struct {
	CommandName  string    `json:"command_name"`
	ChannelID    string    `json:"channel_id"`
	ConfiguredBy string    `json:"configured_by"`
	ConfiguredAt time.Time `json:"configured_at"`
}

// List all response channel configurations for a guild
func (q *Queries) ListResponseChannels(ctx context.Context, guildID string) ([]ListResponseChannelsRow, error) {
	rows, err := q.db.Query(ctx, listResponseChannels, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResponseChannelsRow{}
	for rows.Next() {
		var i ListResponseChannelsRow
		if err := rows.Scan(
			&i.CommandName,
			&i.ChannelID,
			&i.ConfiguredBy,
			&i.ConfiguredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResponseChannel = `-- name: SetResponseChannel :exec
INSERT INTO response_channel_config (guild_id, command_name, channel_id, configured_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (guild_id, command_name) 
DO UPDATE SET 
    channel_id = EXCLUDED.channel_id,
    configured_by = EXCLUDED.configured_by,
    configured_at = NOW()
`

type SetResponseChannelParams struct {
	GuildID      string `json:"guild_id"`
	CommandName  string `json:"command_name"`
	ChannelID    string `json:"channel_id"`
	ConfiguredBy string `json:"configured_by"`
}

// Set response channel for a command (empty command_name = global)
func (q *Queries) SetResponseChannel(ctx context.Context, arg SetResponseChannelParams) error {
	_, err := q.db.Exec(ctx, setResponseChannel,
		arg.GuildID,
		arg.CommandName,
		arg.ChannelID,
		arg.ConfiguredBy,
	)
	return err
}
