// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpsertUser = `-- name: BatchUpsertUser :exec
INSERT INTO users (
    user_id, 
    username, 
    discriminator, 
    display_name, 
    avatar_hash, 
    bot
) VALUES (
    $1, $2, $3, $4, $5, $6
) 
ON CONFLICT (user_id) DO UPDATE SET 
    username = EXCLUDED.username,
    discriminator = EXCLUDED.discriminator,
    display_name = EXCLUDED.display_name,
    avatar_hash = EXCLUDED.avatar_hash,
    bot = EXCLUDED.bot,
    last_updated_at = NOW()
`

type BatchUpsertUserParams struct {
	UserID        string      `json:"user_id"`
	Username      string      `json:"username"`
	Discriminator pgtype.Text `json:"discriminator"`
	DisplayName   pgtype.Text `json:"display_name"`
	AvatarHash    pgtype.Text `json:"avatar_hash"`
	Bot           pgtype.Bool `json:"bot"`
}

func (q *Queries) BatchUpsertUser(ctx context.Context, arg BatchUpsertUserParams) error {
	_, err := q.db.Exec(ctx, batchUpsertUser,
		arg.UserID,
		arg.Username,
		arg.Discriminator,
		arg.DisplayName,
		arg.AvatarHash,
		arg.Bot,
	)
	return err
}

const cleanupOldUsernameChanges = `-- name: CleanupOldUsernameChanges :exec
DELETE FROM username_changelog 
WHERE changed_at < NOW() - INTERVAL '2 years'
`

func (q *Queries) CleanupOldUsernameChanges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldUsernameChanges)
	return err
}

const getActiveUsers = `-- name: GetActiveUsers :many
SELECT user_id, username, discriminator, display_name, avatar_hash, bot, first_seen_at, last_updated_at, last_message_at, is_active FROM users 
WHERE is_active = TRUE 
   AND last_message_at > NOW() - INTERVAL '30 days'
ORDER BY last_message_at DESC
LIMIT $1
`

func (q *Queries) GetActiveUsers(ctx context.Context, limit int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getActiveUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Discriminator,
			&i.DisplayName,
			&i.AvatarHash,
			&i.Bot,
			&i.FirstSeenAt,
			&i.LastUpdatedAt,
			&i.LastMessageAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentUsernameChanges = `-- name: GetRecentUsernameChanges :many
SELECT 
    uc.user_id,
    u.username as current_username,
    uc.old_username,
    uc.new_username,
    uc.changed_at,
    uc.detected_via
FROM username_changelog uc
JOIN users u ON uc.user_id = u.user_id
WHERE uc.changed_at > NOW() - INTERVAL '7 days'
ORDER BY uc.changed_at DESC
LIMIT $1
`

type GetRecentUsernameChangesRow struct {
	UserID          string    `json:"user_id"`
	CurrentUsername string    `json:"current_username"`
	OldUsername     string    `json:"old_username"`
	NewUsername     string    `json:"new_username"`
	ChangedAt       time.Time `json:"changed_at"`
	DetectedVia     string    `json:"detected_via"`
}

func (q *Queries) GetRecentUsernameChanges(ctx context.Context, limit int32) ([]GetRecentUsernameChangesRow, error) {
	rows, err := q.db.Query(ctx, getRecentUsernameChanges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentUsernameChangesRow{}
	for rows.Next() {
		var i GetRecentUsernameChangesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CurrentUsername,
			&i.OldUsername,
			&i.NewUsername,
			&i.ChangedAt,
			&i.DetectedVia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleUsers = `-- name: GetStaleUsers :many
SELECT user_id, username, last_updated_at, last_message_at 
FROM users 
WHERE last_updated_at < NOW() - INTERVAL '24 hours'
   AND (last_message_at IS NULL OR last_message_at < NOW() - INTERVAL '30 days')
ORDER BY last_updated_at ASC
LIMIT $1
`

type GetStaleUsersRow struct {
	UserID        string             `json:"user_id"`
	Username      string             `json:"username"`
	LastUpdatedAt time.Time          `json:"last_updated_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) GetStaleUsers(ctx context.Context, limit int32) ([]GetStaleUsersRow, error) {
	rows, err := q.db.Query(ctx, getStaleUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleUsersRow{}
	for rows.Next() {
		var i GetStaleUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.LastUpdatedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, discriminator, display_name, avatar_hash, bot, first_seen_at, last_updated_at, last_message_at, is_active FROM users 
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Discriminator,
		&i.DisplayName,
		&i.AvatarHash,
		&i.Bot,
		&i.FirstSeenAt,
		&i.LastUpdatedAt,
		&i.LastMessageAt,
		&i.IsActive,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :many
SELECT user_id, username, discriminator, display_name, avatar_hash, bot, first_seen_at, last_updated_at, last_message_at, is_active FROM users 
WHERE username ILIKE $1 
ORDER BY last_message_at DESC NULLS LAST
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUserByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Discriminator,
			&i.DisplayName,
			&i.AvatarHash,
			&i.Bot,
			&i.FirstSeenAt,
			&i.LastUpdatedAt,
			&i.LastMessageAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT 
    u.user_id,
    u.username,
    u.first_seen_at,
    u.last_message_at,
    COUNT(uc.id) as username_changes
FROM users u
LEFT JOIN username_changelog uc ON u.user_id = uc.user_id
WHERE u.user_id = $1
GROUP BY u.user_id, u.username, u.first_seen_at, u.last_message_at
`

type GetUserProfileRow struct {
	UserID          string             `json:"user_id"`
	Username        string             `json:"username"`
	FirstSeenAt     time.Time          `json:"first_seen_at"`
	LastMessageAt   pgtype.Timestamptz `json:"last_message_at"`
	UsernameChanges int64              `json:"username_changes"`
}

func (q *Queries) GetUserProfile(ctx context.Context, userID string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i GetUserProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FirstSeenAt,
		&i.LastMessageAt,
		&i.UsernameChanges,
	)
	return i, err
}

const getUsernameHistory = `-- name: GetUsernameHistory :many
SELECT 
    old_username,
    new_username, 
    old_discriminator,
    new_discriminator,
    changed_at,
    detected_via
FROM username_changelog 
WHERE user_id = $1 
ORDER BY changed_at DESC
LIMIT $2
`

type GetUsernameHistoryParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type GetUsernameHistoryRow struct {
	OldUsername      string      `json:"old_username"`
	NewUsername      string      `json:"new_username"`
	OldDiscriminator pgtype.Text `json:"old_discriminator"`
	NewDiscriminator pgtype.Text `json:"new_discriminator"`
	ChangedAt        time.Time   `json:"changed_at"`
	DetectedVia      string      `json:"detected_via"`
}

func (q *Queries) GetUsernameHistory(ctx context.Context, arg GetUsernameHistoryParams) ([]GetUsernameHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUsernameHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsernameHistoryRow{}
	for rows.Next() {
		var i GetUsernameHistoryRow
		if err := rows.Scan(
			&i.OldUsername,
			&i.NewUsername,
			&i.OldDiscriminator,
			&i.NewDiscriminator,
			&i.ChangedAt,
			&i.DetectedVia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersNeedingRefresh = `-- name: GetUsersNeedingRefresh :many
SELECT user_id FROM users 
WHERE last_updated_at < NOW() - INTERVAL '1 hour'
   OR last_updated_at IS NULL
ORDER BY last_updated_at ASC NULLS FIRST
LIMIT $1
`

func (q *Queries) GetUsersNeedingRefresh(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getUsersNeedingRefresh, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithoutRecentActivity = `-- name: GetUsersWithoutRecentActivity :many
SELECT user_id, username, last_message_at 
FROM users 
WHERE last_message_at < NOW() - INTERVAL '90 days'
   OR last_message_at IS NULL
ORDER BY last_message_at ASC NULLS FIRST
LIMIT $1
`

type GetUsersWithoutRecentActivityRow struct {
	UserID        string             `json:"user_id"`
	Username      string             `json:"username"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) GetUsersWithoutRecentActivity(ctx context.Context, limit int32) ([]GetUsersWithoutRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getUsersWithoutRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWithoutRecentActivityRow{}
	for rows.Next() {
		var i GetUsersWithoutRecentActivityRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.LastMessageAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserInactive = `-- name: MarkUserInactive :exec
UPDATE users 
SET is_active = FALSE, last_updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) MarkUserInactive(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markUserInactive, userID)
	return err
}

const searchUsersByPattern = `-- name: SearchUsersByPattern :many
SELECT user_id, username, discriminator, display_name, avatar_hash, bot, first_seen_at, last_updated_at, last_message_at, is_active FROM users 
WHERE username ILIKE '%' || $1 || '%'
   OR display_name ILIKE '%' || $1 || '%'
ORDER BY 
    CASE WHEN username ILIKE $1 || '%' THEN 0 ELSE 1 END,
    last_message_at DESC NULLS LAST
LIMIT $2
`

type SearchUsersByPatternParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchUsersByPattern(ctx context.Context, arg SearchUsersByPatternParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByPattern, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Discriminator,
			&i.DisplayName,
			&i.AvatarHash,
			&i.Bot,
			&i.FirstSeenAt,
			&i.LastUpdatedAt,
			&i.LastMessageAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLastMessage = `-- name: UpdateUserLastMessage :exec
UPDATE users 
SET last_message_at = $2, last_updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserLastMessageParams struct {
	UserID        string             `json:"user_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) UpdateUserLastMessage(ctx context.Context, arg UpdateUserLastMessageParams) error {
	_, err := q.db.Exec(ctx, updateUserLastMessage, arg.UserID, arg.LastMessageAt)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    user_id, 
    username, 
    discriminator, 
    display_name, 
    avatar_hash, 
    bot,
    last_message_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) 
ON CONFLICT (user_id) DO UPDATE SET 
    username = EXCLUDED.username,
    discriminator = EXCLUDED.discriminator,
    display_name = EXCLUDED.display_name,
    avatar_hash = EXCLUDED.avatar_hash,
    bot = EXCLUDED.bot,
    last_message_at = GREATEST(users.last_message_at, EXCLUDED.last_message_at),
    last_updated_at = NOW()
RETURNING user_id, username, discriminator, display_name, avatar_hash, bot, first_seen_at, last_updated_at, last_message_at, is_active
`

type UpsertUserParams struct {
	UserID        string             `json:"user_id"`
	Username      string             `json:"username"`
	Discriminator pgtype.Text        `json:"discriminator"`
	DisplayName   pgtype.Text        `json:"display_name"`
	AvatarHash    pgtype.Text        `json:"avatar_hash"`
	Bot           pgtype.Bool        `json:"bot"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.UserID,
		arg.Username,
		arg.Discriminator,
		arg.DisplayName,
		arg.AvatarHash,
		arg.Bot,
		arg.LastMessageAt,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Discriminator,
		&i.DisplayName,
		&i.AvatarHash,
		&i.Bot,
		&i.FirstSeenAt,
		&i.LastUpdatedAt,
		&i.LastMessageAt,
		&i.IsActive,
	)
	return i, err
}
